language: php

php:
  - 7.3

before_script:
  - ./vendor/bin/php-coveralls -h
  - mkdir -p coverage-clover/logs
  - phpenv config-rm xdebug.ini

install: 
  - composer install --dev --no-interaction --quiet

script:
  - composer dump
  - phpdbg -qrr -d memory_limit=-1 ./vendor/bin/phpunit -c phpunit.xml
  # - phpdbg -qrr -d memory_limit=-1 ./vendor/bin/phpunit --coverage-clover coverage-clover/logs/clover.xml
  - ls -al coverage-clover/logs

after_success:
  - ./vendor/bin/php-coveralls -v